version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./code:/code  # Assurez-vous que le dossier contenant vos fichiers PHP est monté dans /code
      - ./nginx.conf:/etc/nginx/nginx.conf  # Utilisation de votre configuration Nginx
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./code:/code  # Assurez-vous que vos fichiers PHP sont accessibles dans le conteneur PHP
